{% set name = "treeconfigparser" %}
{% set version = "1.0.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: "b4cbdd420f88716958e5c321d908fd3dcfd64fd1c566ff9ee75ffad780249898"

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
    - numpy
    - path
  run:
    - python
    - numpy
    - path

test:
  imports:
    - treeconfigparser

about:
  home: "https://gitlab.enpc.fr/cerea-da-team/treeconfigparser"
  license: "MIT"
  license_family: "MIT"
  summary: "Custom configuration parser based on a tree"
  doc_url: "https://cerea-da-team.gitlab.enpc.fr/treeconfigparser"
  dev_url: "https://gitlab.enpc.fr/cerea-da-team/treeconfigparser"
