{% set name = "treeconfigparser" %}
{% set version = "1.1.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 58d90d89ce49ea9569016483c8e32a6523798db9bf943a7853863e77f978afdc

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
    - numpy
    - path
  run:
    - python
    - numpy
    - path

test:
  imports:
    - treeconfigparser

about:
  home: "https://github.com/cerea-daml/treeconfigparser"
  license: MIT
  license_family: MIT
  summary: "Custom configuration parser based on a tree"
  doc_url: "https://cerea-daml.github.io/treeconfigparser"
  dev_url: "https://github.com/cerea-daml/treeconfigparser"

